language: go
go:
 - 1.9.x
before_install:
  # Setup dependency management tool
  - curl -L -s https://github.com/golang/dep/releases/download/v0.3.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
install:
  - dep ensure && go install ./cmd/...

 # Specify Import Path (optional)
 # Example: go_import_path: example.org/pkg/foo