# YAML example for encrytion configuration
---
version: v0.1
group : SS512 # Default encryption setup
recipients: 
  # Define all the recipients who can see the encryption message 
  # You can specify which user can see which part of information 
  # in the following section
  - Alice 
  - Bob
  - Carol
encryptionfields: 
  # Details of the encryption fields
  # The format of this part is:
  # ===========================
  # - FIELD_NAME: field_name
  #   AUTHORIZEDUSER :
  #     - user name 1
  #     - user name 2 
  # ===========================  
  # the RECIPIENTS of the FIELD could see the information of 
  # the particular field
  - fieldname : Shipper 
  # For example, AgentForMaster can be revealed by both Alice and Bob
    authorizeduser:
      - Alice
      - Bob
  # - fieldname : AgentForOwner
  # # all means all the recipients can see this part of information
  #   authorizeduser:
  #     - all 
  # - fieldname : MasterInfo
  # # Only Alice can reveal the MasterInfo section
  #   authorizeduser:
  #     - Alice
publickeys:
  # Link each recipient to their public key file
  - userid : Alice
    keyfile : alice_pubkey.yaml
  - userid : Bob
    keyfile : bob_pri_key.json
  - userid : Carol
    keyfile : carol_pri_key.json