---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bftx-config
data:
  seeds: "bftx0,bftx1,bftx2,bftx3"
  validators: "bftx0,bftx1,bftx2,bftx3"
  validator.power: "10"
  genesis.json: |-
    {
      "genesis_time": "2016-04-26T22:00:00Z",
      "chain_id": "chain-IdealX",
      "validators": [],
      "app_hash": ""
    }
  pub_key_nginx.conf: |-
    server {
      listen 80 default_server;
      listen [::]:80 default_server ipv6only=on;
    }